name = "MultiMLDatasets"
uuid = "558b1b0f-be74-4e24-a9cd-57b8a919f62e"
authors = ["Manuel Berkemeier <manuelbb@mail.uni-paderborn.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
